chat/urls.py
from django.conf.urls import url

from . import views

app_name = 'chat'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^send/$', views.send, name='send'),
    url(r'^messages/$', views.get_messages, name='messages'),
    url(r'^sighin/$', views.sigh_in, name='sighin'),
    url(r'^sighout/$', views.sigh_out, name='sighout'),
    url(r'^login/$', views.login_site, name='login'),
]

pchat/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import reverse


def redirect(request):
    return HttpResponseRedirect(reverse('chat:index'))

urlpatterns = [
    url(r'^$', redirect),
    url(r'^chat/', include('chat.urls')),
    url(r'^admin/', admin.site.urls),
]

chat/models.py
from django.db import models


class Messages(models.Model):
    message_text = models.CharField(max_length=500)
    post_date = models.DateTimeField('date posted')

    def __str__(self):
        return self.message_text

chat/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseForbidden
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from chat.models import Messages


def get_list_latest_messages():
    return reversed(Messages.objects.filter(
        post_date__lte=timezone.now()
    ).order_by('-post_date')[:15])


def index(request):
    if request.user.is_authenticated():
        template = loader.get_template('chat/index.html')
        context = {
            'latest_messages_list': get_list_latest_messages(),
            'user_name': request.user,
        }
        return HttpResponse(template.render(context, request))
    else:
        return HttpResponseRedirect(reverse('chat:login'))


def send(request):
    try:
        message = Messages(message_text=request.POST['message'], post_date=timezone.now())
    except (KeyError, Messages.DoesNotExist):
        return HttpResponse('<h1><font color="red">Miss message</font></h1>')
    message.save()
    return HttpResponseRedirect(reverse('chat:index'))


def get_messages(request):
    list_messages = get_list_latest_messages()
    array_messages = []
    for message in list_messages:
        array_messages.append(message.message_text)
    return HttpResponse(json.dumps(list(array_messages)), content_type="application/json")


def sigh_in(request):
    try:
        login_str = request.POST['login']
        password_str = request.POST['password']
        if str(login_str.strip()) == '' and str(password_str.strip()) == '':
            raise KeyError
    except KeyError:
        return HttpResponseForbidden('<h1><font color="red">Miss login/password</font></h1>')

    user = authenticate(username=login_str, password=password_str)
    if user is not None:
        if user.is_active:
            login(request, user)
            return HttpResponseRedirect(reverse('chat:index'))
        else:
            return HttpResponseForbidden('<h1><font color="red">Account disabled</font></h1>')
    else:
        if User.objects.filter(username=login_str).exists():
            return HttpResponseForbidden('<h1><font color="red">Wrong password</font></h1>')
        else:
            user = User.objects.create_user(login_str, '', password_str)
            user.save()
            login(request, user)
            return HttpResponseRedirect(reverse('chat:index'))


def login_site(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse('chat:index'))
    else:
        template = loader.get_template('chat/login.html')
        return HttpResponse(template.render({}, request))


def sigh_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('chat:index'))

chat/templates/chat/index.html
{% load staticfiles %}

<script src="{% static 'chat/scripts/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'chat/scripts/chat_history_refresh' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'chat/css/style.css' %}" />

<a id="out" href="{% url 'chat:sighout' %}">"Выйти"</a>

{% if latest_messages_list %}
<div id="history">
    <ul>
        {% for message in latest_messages_list %}
            <li>{{message.message_text}}</li>
        {% endfor %}
    </ul>
</div>
{% else %}
<p>History chat is empty</p>
{% endif %}

{% csrf_token %}

<hr><br/>
<label>Ваше сообщение: </label>
<br/><br/>
<input type="text" id="message" name="message" size="auto" />
<br/><br/>
<input type="button" id="send" onclick="send_get_new_message()" value="Отправить" />
<a type="hidden" id = "message_url" href="{% url 'chat:messages' %}"/>
<a type="hidden" id = "send_url" href="{% url 'chat:send' %}"/>
<a type="hidden" id = "user_name" href="{{ user_name }}"/>

chat/templates/chat/login.html
{% load staticfiles %}

<script src="{% static 'chat/scripts/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'chat/scripts/chat_history_refresh' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'chat/css/style.css' %}" />

<br/>
<br/>
<form action="{% url 'chat:sighin' %}" method="post">
{% csrf_token %}
    <label>Логин: </label>
    <input type="text" name="login" id="login" value="" />
    <br/>
    <br/>
    <label>Пароль:</label>
    <input type="password" name="password" id="password" value="" />
    <br/>
    <br/>
<input type="submit" id="send" value="Войти/Зарегистрироваться" />
</form>